// Code generated by protoc-gen-psrpc v0.6.0, DO NOT EDIT.
// source: rpc/agent_dispatch.proto

package rpc

import (
	"context"

	"github.com/vibtreeofficial/psrpc"
	"github.com/vibtreeofficial/psrpc/pkg/client"
	"github.com/vibtreeofficial/psrpc/pkg/info"
	"github.com/vibtreeofficial/psrpc/pkg/rand"
	"github.com/vibtreeofficial/psrpc/pkg/server"
	"github.com/vibtreeofficial/psrpc/version"
)
import media_router3 "github.com/vibtreeofficial/protocol/media-router"

var _ = version.PsrpcVersion_0_6

// ======================================
// AgentDispatchInternal Client Interface
// ======================================

type AgentDispatchInternalClient[RoomTopicType ~string] interface {
	CreateDispatch(ctx context.Context, room RoomTopicType, req *media_router3.AgentDispatch, opts ...psrpc.RequestOption) (*media_router3.AgentDispatch, error)

	DeleteDispatch(ctx context.Context, room RoomTopicType, req *media_router3.DeleteAgentDispatchRequest, opts ...psrpc.RequestOption) (*media_router3.AgentDispatch, error)

	ListDispatch(ctx context.Context, room RoomTopicType, req *media_router3.ListAgentDispatchRequest, opts ...psrpc.RequestOption) (*media_router3.ListAgentDispatchResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ==========================================
// AgentDispatchInternal ServerImpl Interface
// ==========================================

type AgentDispatchInternalServerImpl interface {
	CreateDispatch(context.Context, *media_router3.AgentDispatch) (*media_router3.AgentDispatch, error)

	DeleteDispatch(context.Context, *media_router3.DeleteAgentDispatchRequest) (*media_router3.AgentDispatch, error)

	ListDispatch(context.Context, *media_router3.ListAgentDispatchRequest) (*media_router3.ListAgentDispatchResponse, error)
}

// ======================================
// AgentDispatchInternal Server Interface
// ======================================

type AgentDispatchInternalServer[RoomTopicType ~string] interface {
	RegisterCreateDispatchTopic(room RoomTopicType) error
	DeregisterCreateDispatchTopic(room RoomTopicType)
	RegisterDeleteDispatchTopic(room RoomTopicType) error
	DeregisterDeleteDispatchTopic(room RoomTopicType)
	RegisterListDispatchTopic(room RoomTopicType) error
	DeregisterListDispatchTopic(room RoomTopicType)
	RegisterAllRoomTopics(room RoomTopicType) error
	DeregisterAllRoomTopics(room RoomTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ============================
// AgentDispatchInternal Client
// ============================

type agentDispatchInternalClient[RoomTopicType ~string] struct {
	client *client.RPCClient
}

// NewAgentDispatchInternalClient creates a psrpc client that implements the AgentDispatchInternalClient interface.
func NewAgentDispatchInternalClient[RoomTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (AgentDispatchInternalClient[RoomTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "AgentDispatchInternal",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("CreateDispatch", false, false, true, true)
	sd.RegisterMethod("DeleteDispatch", false, false, true, true)
	sd.RegisterMethod("ListDispatch", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &agentDispatchInternalClient[RoomTopicType]{
		client: rpcClient,
	}, nil
}

func (c *agentDispatchInternalClient[RoomTopicType]) CreateDispatch(ctx context.Context, room RoomTopicType, req *media_router3.AgentDispatch, opts ...psrpc.RequestOption) (*media_router3.AgentDispatch, error) {
	return client.RequestSingle[*media_router3.AgentDispatch](ctx, c.client, "CreateDispatch", []string{string(room)}, req, opts...)
}

func (c *agentDispatchInternalClient[RoomTopicType]) DeleteDispatch(ctx context.Context, room RoomTopicType, req *media_router3.DeleteAgentDispatchRequest, opts ...psrpc.RequestOption) (*media_router3.AgentDispatch, error) {
	return client.RequestSingle[*media_router3.AgentDispatch](ctx, c.client, "DeleteDispatch", []string{string(room)}, req, opts...)
}

func (c *agentDispatchInternalClient[RoomTopicType]) ListDispatch(ctx context.Context, room RoomTopicType, req *media_router3.ListAgentDispatchRequest, opts ...psrpc.RequestOption) (*media_router3.ListAgentDispatchResponse, error) {
	return client.RequestSingle[*media_router3.ListAgentDispatchResponse](ctx, c.client, "ListDispatch", []string{string(room)}, req, opts...)
}

func (s *agentDispatchInternalClient[RoomTopicType]) Close() {
	s.client.Close()
}

// ============================
// AgentDispatchInternal Server
// ============================

type agentDispatchInternalServer[RoomTopicType ~string] struct {
	svc AgentDispatchInternalServerImpl
	rpc *server.RPCServer
}

// NewAgentDispatchInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewAgentDispatchInternalServer[RoomTopicType ~string](svc AgentDispatchInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (AgentDispatchInternalServer[RoomTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "AgentDispatchInternal",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("CreateDispatch", false, false, true, true)
	sd.RegisterMethod("DeleteDispatch", false, false, true, true)
	sd.RegisterMethod("ListDispatch", false, false, true, true)
	return &agentDispatchInternalServer[RoomTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *agentDispatchInternalServer[RoomTopicType]) RegisterCreateDispatchTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "CreateDispatch", []string{string(room)}, s.svc.CreateDispatch, nil)
}

func (s *agentDispatchInternalServer[RoomTopicType]) DeregisterCreateDispatchTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("CreateDispatch", []string{string(room)})
}

func (s *agentDispatchInternalServer[RoomTopicType]) RegisterDeleteDispatchTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "DeleteDispatch", []string{string(room)}, s.svc.DeleteDispatch, nil)
}

func (s *agentDispatchInternalServer[RoomTopicType]) DeregisterDeleteDispatchTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("DeleteDispatch", []string{string(room)})
}

func (s *agentDispatchInternalServer[RoomTopicType]) RegisterListDispatchTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "ListDispatch", []string{string(room)}, s.svc.ListDispatch, nil)
}

func (s *agentDispatchInternalServer[RoomTopicType]) DeregisterListDispatchTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("ListDispatch", []string{string(room)})
}

func (s *agentDispatchInternalServer[RoomTopicType]) allRoomTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterCreateDispatchTopic, s.DeregisterCreateDispatchTopic),
		server.NewRegisterer(s.RegisterDeleteDispatchTopic, s.DeregisterDeleteDispatchTopic),
		server.NewRegisterer(s.RegisterListDispatchTopic, s.DeregisterListDispatchTopic),
	}
}

func (s *agentDispatchInternalServer[RoomTopicType]) RegisterAllRoomTopics(room RoomTopicType) error {
	return s.allRoomTopicRegisterers().Register(room)
}

func (s *agentDispatchInternalServer[RoomTopicType]) DeregisterAllRoomTopics(room RoomTopicType) {
	s.allRoomTopicRegisterers().Deregister(room)
}

func (s *agentDispatchInternalServer[RoomTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *agentDispatchInternalServer[RoomTopicType]) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor1 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x15, 0x0f, 0x41, 0x17, 0x09, 0x28, 0x65, 0x3d, 0xe9, 0xc1, 0xea, 0x65, 0x17,
	0xf4, 0x09, 0xd4, 0x5e, 0x04, 0x4f, 0x1e, 0xbd, 0x2c, 0x49, 0x3a, 0x6d, 0x07, 0xb2, 0x99, 0x38,
	0x99, 0xd5, 0x67, 0xf0, 0x75, 0x7c, 0x27, 0xdf, 0x43, 0xba, 0x55, 0x69, 0xa0, 0x2a, 0x78, 0x09,
	0x64, 0xbe, 0xf9, 0xff, 0xef, 0x30, 0x6a, 0xc4, 0xd1, 0x35, 0x66, 0x0e, 0x41, 0xda, 0x29, 0xa6,
	0x68, 0xc4, 0x2d, 0xea, 0xc8, 0x24, 0xa4, 0xb7, 0x39, 0xba, 0x6a, 0x9f, 0xa2, 0x20, 0x85, 0xb4,
	0x9a, 0x55, 0x27, 0x1d, 0x4c, 0xd1, 0xb4, 0x4c, 0xbd, 0x00, 0xb7, 0x9b, 0x62, 0x97, 0xef, 0x5b,
	0xea, 0xf0, 0x7a, 0x09, 0x26, 0x9f, 0xf3, 0xbb, 0x20, 0xc0, 0xc1, 0x78, 0x6d, 0x55, 0x79, 0xcb,
	0x60, 0x04, 0xbe, 0x88, 0x3e, 0xae, 0xd7, 0xfb, 0xea, 0x2c, 0x56, 0xfd, 0x06, 0x4f, 0x8f, 0xde,
	0x5e, 0x0b, 0x7d, 0x50, 0x54, 0xa5, 0xda, 0x61, 0xa2, 0x4e, 0x0f, 0xef, 0xa8, 0xd0, 0xa4, 0xca,
	0x09, 0x78, 0x58, 0x73, 0x9c, 0xe7, 0x35, 0x2b, 0x9a, 0x95, 0x3d, 0xc0, 0x53, 0x0f, 0x49, 0xfe,
	0x27, 0x7c, 0x51, 0x7b, 0xf7, 0x98, 0xbe, 0xf7, 0xf4, 0x59, 0x5e, 0xb2, 0x64, 0x1b, 0x65, 0xe3,
	0x3f, 0xf7, 0x52, 0xa4, 0x90, 0xe0, 0x27, 0xf1, 0xcd, 0xc5, 0xe3, 0x78, 0x8e, 0xb2, 0xe8, 0x6d,
	0xed, 0xa8, 0x6b, 0x9e, 0xd1, 0x0a, 0x03, 0xd0, 0x6c, 0x86, 0x0e, 0x8d, 0x6f, 0x86, 0x5b, 0x38,
	0xf2, 0x0d, 0x47, 0x67, 0x77, 0x87, 0xdf, 0xd5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x03,
	0xd8, 0xb8, 0xec, 0x01, 0x00, 0x00,
}
