// Code generated by protoc-gen-psrpc v0.6.0, DO NOT EDIT.
// source: rpc/room.proto

package rpc

import (
	"context"

	"github.com/vibtreeofficial/psrpc"
	"github.com/vibtreeofficial/psrpc/pkg/client"
	"github.com/vibtreeofficial/psrpc/pkg/info"
	"github.com/vibtreeofficial/psrpc/pkg/rand"
	"github.com/vibtreeofficial/psrpc/pkg/server"
	"github.com/vibtreeofficial/psrpc/version"
)
import media_router1 "github.com/vibtreeofficial/protocol/media-router"
import media_router6 "github.com/vibtreeofficial/protocol/media-router"

var _ = version.PsrpcVersion_0_6

// =====================
// Room Client Interface
// =====================

type RoomClient[RoomTopicType ~string] interface {
	DeleteRoom(ctx context.Context, room RoomTopicType, req *media_router6.DeleteRoomRequest, opts ...psrpc.RequestOption) (*media_router6.DeleteRoomResponse, error)

	SendData(ctx context.Context, room RoomTopicType, req *media_router6.SendDataRequest, opts ...psrpc.RequestOption) (*media_router6.SendDataResponse, error)

	UpdateRoomMetadata(ctx context.Context, room RoomTopicType, req *media_router6.UpdateRoomMetadataRequest, opts ...psrpc.RequestOption) (*media_router1.Room, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// =========================
// Room ServerImpl Interface
// =========================

type RoomServerImpl interface {
	DeleteRoom(context.Context, *media_router6.DeleteRoomRequest) (*media_router6.DeleteRoomResponse, error)

	SendData(context.Context, *media_router6.SendDataRequest) (*media_router6.SendDataResponse, error)

	UpdateRoomMetadata(context.Context, *media_router6.UpdateRoomMetadataRequest) (*media_router1.Room, error)
}

// =====================
// Room Server Interface
// =====================

type RoomServer[RoomTopicType ~string] interface {
	RegisterDeleteRoomTopic(room RoomTopicType) error
	DeregisterDeleteRoomTopic(room RoomTopicType)
	RegisterSendDataTopic(room RoomTopicType) error
	DeregisterSendDataTopic(room RoomTopicType)
	RegisterUpdateRoomMetadataTopic(room RoomTopicType) error
	DeregisterUpdateRoomMetadataTopic(room RoomTopicType)
	RegisterAllRoomTopics(room RoomTopicType) error
	DeregisterAllRoomTopics(room RoomTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ===========
// Room Client
// ===========

type roomClient[RoomTopicType ~string] struct {
	client *client.RPCClient
}

// NewRoomClient creates a psrpc client that implements the RoomClient interface.
func NewRoomClient[RoomTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (RoomClient[RoomTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Room",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("DeleteRoom", false, false, true, true)
	sd.RegisterMethod("SendData", false, false, true, true)
	sd.RegisterMethod("UpdateRoomMetadata", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &roomClient[RoomTopicType]{
		client: rpcClient,
	}, nil
}

func (c *roomClient[RoomTopicType]) DeleteRoom(ctx context.Context, room RoomTopicType, req *media_router6.DeleteRoomRequest, opts ...psrpc.RequestOption) (*media_router6.DeleteRoomResponse, error) {
	return client.RequestSingle[*media_router6.DeleteRoomResponse](ctx, c.client, "DeleteRoom", []string{string(room)}, req, opts...)
}

func (c *roomClient[RoomTopicType]) SendData(ctx context.Context, room RoomTopicType, req *media_router6.SendDataRequest, opts ...psrpc.RequestOption) (*media_router6.SendDataResponse, error) {
	return client.RequestSingle[*media_router6.SendDataResponse](ctx, c.client, "SendData", []string{string(room)}, req, opts...)
}

func (c *roomClient[RoomTopicType]) UpdateRoomMetadata(ctx context.Context, room RoomTopicType, req *media_router6.UpdateRoomMetadataRequest, opts ...psrpc.RequestOption) (*media_router1.Room, error) {
	return client.RequestSingle[*media_router1.Room](ctx, c.client, "UpdateRoomMetadata", []string{string(room)}, req, opts...)
}

func (s *roomClient[RoomTopicType]) Close() {
	s.client.Close()
}

// ===========
// Room Server
// ===========

type roomServer[RoomTopicType ~string] struct {
	svc RoomServerImpl
	rpc *server.RPCServer
}

// NewRoomServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewRoomServer[RoomTopicType ~string](svc RoomServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (RoomServer[RoomTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Room",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("DeleteRoom", false, false, true, true)
	sd.RegisterMethod("SendData", false, false, true, true)
	sd.RegisterMethod("UpdateRoomMetadata", false, false, true, true)
	return &roomServer[RoomTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *roomServer[RoomTopicType]) RegisterDeleteRoomTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "DeleteRoom", []string{string(room)}, s.svc.DeleteRoom, nil)
}

func (s *roomServer[RoomTopicType]) DeregisterDeleteRoomTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("DeleteRoom", []string{string(room)})
}

func (s *roomServer[RoomTopicType]) RegisterSendDataTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "SendData", []string{string(room)}, s.svc.SendData, nil)
}

func (s *roomServer[RoomTopicType]) DeregisterSendDataTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("SendData", []string{string(room)})
}

func (s *roomServer[RoomTopicType]) RegisterUpdateRoomMetadataTopic(room RoomTopicType) error {
	return server.RegisterHandler(s.rpc, "UpdateRoomMetadata", []string{string(room)}, s.svc.UpdateRoomMetadata, nil)
}

func (s *roomServer[RoomTopicType]) DeregisterUpdateRoomMetadataTopic(room RoomTopicType) {
	s.rpc.DeregisterHandler("UpdateRoomMetadata", []string{string(room)})
}

func (s *roomServer[RoomTopicType]) allRoomTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterDeleteRoomTopic, s.DeregisterDeleteRoomTopic),
		server.NewRegisterer(s.RegisterSendDataTopic, s.DeregisterSendDataTopic),
		server.NewRegisterer(s.RegisterUpdateRoomMetadataTopic, s.DeregisterUpdateRoomMetadataTopic),
	}
}

func (s *roomServer[RoomTopicType]) RegisterAllRoomTopics(room RoomTopicType) error {
	return s.allRoomTopicRegisterers().Register(room)
}

func (s *roomServer[RoomTopicType]) DeregisterAllRoomTopics(room RoomTopicType) {
	s.allRoomTopicRegisterers().Deregister(room)
}

func (s *roomServer[RoomTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *roomServer[RoomTopicType]) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor7 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xa9, 0x2e, 0x22, 0x01, 0x17, 0x99, 0x83, 0x1f, 0x05, 0x3f, 0xf0, 0xb2, 0x78, 0x69,
	0x41, 0xdf, 0x40, 0xf6, 0xea, 0x65, 0xc5, 0x8b, 0x97, 0x25, 0x4d, 0x66, 0xd7, 0x40, 0xd3, 0x89,
	0xd3, 0xa9, 0xef, 0xe0, 0xeb, 0x78, 0xf7, 0xdd, 0xa4, 0x5d, 0x42, 0x0d, 0x52, 0xf6, 0x12, 0x98,
	0xf9, 0xff, 0xf2, 0xff, 0x85, 0xa8, 0x39, 0x07, 0x53, 0x32, 0x91, 0x2f, 0x02, 0x93, 0x10, 0x1c,
	0x72, 0x30, 0xf9, 0x09, 0x05, 0x71, 0xd4, 0xb4, 0xbb, 0x5d, 0x7e, 0xe9, 0xd1, 0x3a, 0xbd, 0x66,
	0xea, 0x04, 0x79, 0xed, 0xc9, 0x62, 0x1d, 0xa3, 0xf3, 0x24, 0x1a, 0x7b, 0x1e, 0x7e, 0x0e, 0xd4,
	0x6c, 0x45, 0xe4, 0x61, 0xab, 0xd4, 0x12, 0x6b, 0x14, 0x1c, 0xa6, 0x9b, 0xe2, 0xef, 0x85, 0x62,
	0x4c, 0x56, 0xf8, 0xd1, 0x61, 0x2b, 0xf9, 0xed, 0x34, 0xd0, 0x06, 0x6a, 0x5a, 0xbc, 0x3b, 0xfb,
	0xfe, 0xca, 0xe0, 0x34, 0xcb, 0xe7, 0x6a, 0xd6, 0xfb, 0x60, 0x38, 0x2f, 0x32, 0xd0, 0xea, 0xf8,
	0x05, 0x1b, 0xbb, 0xd4, 0xa2, 0xe1, 0x2a, 0x6d, 0x89, 0xfb, 0x28, 0xb9, 0x9e, 0x8a, 0xf7, 0x28,
	0x9c, 0x82, 0xd7, 0x60, 0xf5, 0xee, 0x41, 0xcf, 0x28, 0xda, 0xf6, 0xb2, 0x45, 0xda, 0xf6, 0x9f,
	0x88, 0x5a, 0x48, 0xc1, 0x1e, 0x99, 0x52, 0x3d, 0xdd, 0xbf, 0x2d, 0xb6, 0x4e, 0xde, 0xbb, 0xaa,
	0x30, 0xe4, 0xcb, 0x4f, 0x57, 0x09, 0x23, 0xd2, 0x66, 0xe3, 0x8c, 0xd3, 0x75, 0x39, 0xfc, 0xb1,
	0xa1, 0xba, 0xe4, 0x60, 0xaa, 0xa3, 0x61, 0x7a, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x7b,
	0x78, 0x9a, 0xcb, 0x01, 0x00, 0x00,
}
