// Copyright 2023 VibTree Official
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: media_router_agent_dispatch.proto

package media_router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAgentDispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentName string `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Room      string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Metadata  string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CreateAgentDispatchRequest) Reset() {
	*x = CreateAgentDispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentDispatchRequest) ProtoMessage() {}

func (x *CreateAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentDispatchRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *CreateAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CreateAgentDispatchRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type RoomAgentDispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentName string `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Metadata  string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *RoomAgentDispatch) Reset() {
	*x = RoomAgentDispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAgentDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAgentDispatch) ProtoMessage() {}

func (x *RoomAgentDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAgentDispatch.ProtoReflect.Descriptor instead.
func (*RoomAgentDispatch) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *RoomAgentDispatch) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RoomAgentDispatch) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type DeleteAgentDispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DispatchId string `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	Room       string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *DeleteAgentDispatchRequest) Reset() {
	*x = DeleteAgentDispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentDispatchRequest) ProtoMessage() {}

func (x *DeleteAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAgentDispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *DeleteAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ListAgentDispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DispatchId string `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"` // if set, only the dispatch whose id is given will be returned
	Room       string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                               // name of the room to list agents for. Must be set.
}

func (x *ListAgentDispatchRequest) Reset() {
	*x = ListAgentDispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentDispatchRequest) ProtoMessage() {}

func (x *ListAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*ListAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentDispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *ListAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ListAgentDispatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentDispatches []*AgentDispatch `protobuf:"bytes,1,rep,name=agent_dispatches,json=agentDispatches,proto3" json:"agent_dispatches,omitempty"`
}

func (x *ListAgentDispatchResponse) Reset() {
	*x = ListAgentDispatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentDispatchResponse) ProtoMessage() {}

func (x *ListAgentDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentDispatchResponse.ProtoReflect.Descriptor instead.
func (*ListAgentDispatchResponse) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentDispatchResponse) GetAgentDispatches() []*AgentDispatch {
	if x != nil {
		return x.AgentDispatches
	}
	return nil
}

type AgentDispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentName string              `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Room      string              `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Metadata  string              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	State     *AgentDispatchState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *AgentDispatch) Reset() {
	*x = AgentDispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDispatch) ProtoMessage() {}

func (x *AgentDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDispatch.ProtoReflect.Descriptor instead.
func (*AgentDispatch) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{5}
}

func (x *AgentDispatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDispatch) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentDispatch) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentDispatch) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AgentDispatch) GetState() *AgentDispatchState {
	if x != nil {
		return x.State
	}
	return nil
}

type AgentDispatchState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// For dispatches of tyoe JT_ROOM, there will be at most 1 job.
	// For dispatches of type JT_PUBLISHER, there will be 1 per publisher.
	Jobs      []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt int64  `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *AgentDispatchState) Reset() {
	*x = AgentDispatchState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_media_router_agent_dispatch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDispatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDispatchState) ProtoMessage() {}

func (x *AgentDispatchState) ProtoReflect() protoreflect.Message {
	mi := &file_media_router_agent_dispatch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDispatchState.ProtoReflect.Descriptor instead.
func (*AgentDispatchState) Descriptor() ([]byte, []int) {
	return file_media_router_agent_dispatch_proto_rawDescGZIP(), []int{6}
}

func (x *AgentDispatchState) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *AgentDispatchState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AgentDispatchState) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

var File_media_router_agent_dispatch_proto protoreflect.FileDescriptor

var file_media_router_agent_dispatch_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x1a, 0x18, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x1a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x4f, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x63, 0x0a, 0x19,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x0f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x22, 0xa6, 0x01, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x79, 0x0a, 0x12, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x4a, 0x6f,
	0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xa9, 0x02, 0x0a, 0x14, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x28, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x57, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x28, 0x2e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x5f, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x26, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x5b, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x69, 0x62, 0x74, 0x72, 0x65, 0x65, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2d, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0xaa, 0x02, 0x11, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xea, 0x02, 0x12, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_media_router_agent_dispatch_proto_rawDescOnce sync.Once
	file_media_router_agent_dispatch_proto_rawDescData = file_media_router_agent_dispatch_proto_rawDesc
)

func file_media_router_agent_dispatch_proto_rawDescGZIP() []byte {
	file_media_router_agent_dispatch_proto_rawDescOnce.Do(func() {
		file_media_router_agent_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(file_media_router_agent_dispatch_proto_rawDescData)
	})
	return file_media_router_agent_dispatch_proto_rawDescData
}

var file_media_router_agent_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_media_router_agent_dispatch_proto_goTypes = []interface{}{
	(*CreateAgentDispatchRequest)(nil), // 0: media_router.CreateAgentDispatchRequest
	(*RoomAgentDispatch)(nil),          // 1: media_router.RoomAgentDispatch
	(*DeleteAgentDispatchRequest)(nil), // 2: media_router.DeleteAgentDispatchRequest
	(*ListAgentDispatchRequest)(nil),   // 3: media_router.ListAgentDispatchRequest
	(*ListAgentDispatchResponse)(nil),  // 4: media_router.ListAgentDispatchResponse
	(*AgentDispatch)(nil),              // 5: media_router.AgentDispatch
	(*AgentDispatchState)(nil),         // 6: media_router.AgentDispatchState
	(*Job)(nil),                        // 7: media_router.Job
}
var file_media_router_agent_dispatch_proto_depIdxs = []int32{
	5, // 0: media_router.ListAgentDispatchResponse.agent_dispatches:type_name -> media_router.AgentDispatch
	6, // 1: media_router.AgentDispatch.state:type_name -> media_router.AgentDispatchState
	7, // 2: media_router.AgentDispatchState.jobs:type_name -> media_router.Job
	0, // 3: media_router.AgentDispatchService.CreateDispatch:input_type -> media_router.CreateAgentDispatchRequest
	2, // 4: media_router.AgentDispatchService.DeleteDispatch:input_type -> media_router.DeleteAgentDispatchRequest
	3, // 5: media_router.AgentDispatchService.ListDispatch:input_type -> media_router.ListAgentDispatchRequest
	5, // 6: media_router.AgentDispatchService.CreateDispatch:output_type -> media_router.AgentDispatch
	5, // 7: media_router.AgentDispatchService.DeleteDispatch:output_type -> media_router.AgentDispatch
	4, // 8: media_router.AgentDispatchService.ListDispatch:output_type -> media_router.ListAgentDispatchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_media_router_agent_dispatch_proto_init() }
func file_media_router_agent_dispatch_proto_init() {
	if File_media_router_agent_dispatch_proto != nil {
		return
	}
	file_media_router_agent_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_media_router_agent_dispatch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgentDispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAgentDispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgentDispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentDispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentDispatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_media_router_agent_dispatch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDispatchState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_media_router_agent_dispatch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_router_agent_dispatch_proto_goTypes,
		DependencyIndexes: file_media_router_agent_dispatch_proto_depIdxs,
		MessageInfos:      file_media_router_agent_dispatch_proto_msgTypes,
	}.Build()
	File_media_router_agent_dispatch_proto = out.File
	file_media_router_agent_dispatch_proto_rawDesc = nil
	file_media_router_agent_dispatch_proto_goTypes = nil
	file_media_router_agent_dispatch_proto_depIdxs = nil
}
